spring:
  application:
    name: product-cache-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true

info:
  component: Product Cache Service
logging:
  level:
    root:
    com.pblgllgs: DEBUG
server:
  port: 9791

---

spring:
  cache:
    type: redis
  config:
    activate:
      on-profile: stage
  data:
    redis:
      host: redis
      port: 6379

feign:
  product-service:
    name: product-service
    url: http://zuul-edge-server:8762

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

---

spring:
  cache:
    type: redis
  config:
    activate:
      on-profile: stage
  data:
    redis:
      host: redis
      port: 6379

feign:
  product-service:
    name: product-service
    url: http://zuul-edge-server:8762

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
