spring:
  application:
    name: zuul-edge-server
  profiles:
    active: localhost

info:
  component: Zuul Edge Server

zuul:
  routes:
    product-service:
      path: /api/1.0/product/**
      serviceId: product-service
      strip-prefix: false
    product-cache-service:
      path: /api/1.0/product-cache/**
      serviceId: product-cache-service
      strip-prefix: false

server:
  port: 8762

---
spring:
  profiles: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}


---
spring:
  profiles: stage

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

